project:
  type: website

website:
  title: "My Visual Analytics Journey"
  navbar:
    logo: /images/site-logo.png
    logo-alt: "My Visual Analytics Journey"
    left:
    - text: "Hands-on Exercises"
      menu:
      - text: "Hands-on Exercise_1"
        href: "HO_EX01.html"
      - text: "Hands-on Exercise_2"
        href: "HO_EX02.html"
      - text: "Hands-on Exercise_3"
        href: "HO_EX03.html"
      - text: "Hands-on Exercise_4"
        href: "HO_EX04.html"
      - text: "Hands-on Exercise_5"
        href: "HO_EX05.html"
    - text: "In-Class Exercises"
      menu:
      - text: "In-Class Exercise_1"
        href: "IC_EX01.html"
      - text: "In-Class Exercise_2"
        href: "IC_EX02.html"
      - text: "In-Class Exercise_3"
        href: "IC_EX03.html"
      - text: "In-Class Exercise_4"
        href: "IC_EX04.html"
      - text: "In-Class Exercise_5"
        href: "IC_EX05.html"
    - text: "Take-Home Exercises"
      menu:
      - text: "Take-Home Exercise_1"
        href: "TH_EX01.html"
      - text: "Take-Home Exercise_2"
        href: "TH_EX02.html"
    right:
      - href: index.qmd
        text: "<img src='/images/home-icon.png' width='88' height='78' alt='Home'>"
      - href: about.qmd
        text: "<img src='/images/about-icon.png' width='88' height='78' alt='About'>"

  sidebar:
    - id: ho_ex05
      title: "Hands-on Exercise 5"
      style: "docked"
      collapse-level: 2
      contents:
        - text: "Overview"
          href: HO_EX05.qmd
        - section: "Chapters"
          contents:
            - text: "6. Visual Correlation Analysis"
              href: HO_EX05_chap06.qmd
            - text: "13. Ternary Plot"
              href: HO_EX05_chap13.qmd
            - text: "14. Heatmap"
              href: HO_EX05_chap14.qmd
            - text: "15. Parallel Coordinates"
              href: HO_EX05_chap15.qmd
            - text: "16. Treemap"
              href: HO_EX05_chap16.qmd
    - id: th-ex01
      title: "Take-home Exercise 1"
      style: "docked"
      contents:
        - href: TH_EX01.qmd
          text: "Technical Report"
        - href: TH_EX01_Slides.html
          text: "Executive Summary Slides"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

