project:
  type: website

website:
  title: "ISSS608-VAA_my"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
      - text: "Hand-on Exercise_1"
        href: "HO_EX01.html"
    - text: "In-Class Exercises"
      menu:
      - text: "In-Class Exercise_1"
        href: "IC_EX01.html"
    - text: "Take-Home Exercises"
      menu:
      - text: "Take-Home Exercise_1"
        href: "TM_EX01.html"
    right:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

